version: '3'
volumes:
    node_modules:
services:
  app:
    build:
        context: ./app
        dockerfile: Dockerfile.dev
    volumes:
        - ./app:/usr/src/app
        - node_modules:/usr/src/app/node_modules
    environment:
        PORT: 9999
    expose:
      - "9999"
    ports:
        - "9999:9999"
    command: >
      sh -c "npm run start"